### ISSUE TITLE
Video controls, buttons are not visible on the player

### ISSUE THREAD

**Issue by ridhwaans** [Lucasmg37/react-netflix-player#20]
I am using the ReactNetflixPlayer in a React application  
First, I installed via `npm install react-netflix-player` and imported `import ReactNetflixPlayer from "react-netflix-player"`  
```
<div>
      <ReactNetflixPlayer 
          fullPlayer 
          autoPlay
          startPosition = { 0 }
          overlayEnabled
          src={url_path} 
          title={title}
          playerLanguage = "en"/>
  </div>
```
There is no controls or icons for the play/pause button, rewind, fast-forward, volume, go next, episode list, settings or fullscreen  

All the player buttons seen in the demo and readme are missing  
Only one button is showing which is the list of choosing playback speed i..e 1x, 1.25x, 2x etc  

Perhaps the type of the video source does not allow the controls to be showing?  

edit:
it looks like a css issue. not everything is brought to front
![image](https://user-images.githubusercontent.com/1103336/112491202-77b53400-8d56-11eb-9070-b53e47f19d33.png)

**Comment by Lucasmg37** [comment]
Hey @ridhwaans, I did some tests with a empty react project and I dint could reproduze this error.

I am thinking that can have a style of your application applying in svgs of the player.
Can you check this please? 

But anyway, send me what browser this error occurred and the version of react you are using.

Thanks for your feedback.

Sorry by my English.

I am starting in this language.

**Comment by ridhwaans** [comment]
this has been resolved
