### ISSUE TITLE
Unable to configure playback rate

### ISSUE THREAD

**Issue by AayushGour** [Lucasmg37/react-netflix-player#31]
Hi. I wanted to configure the playback rate in the player and set it to custom values. 

Is there any way to do it?

Also, in the latest release (1.1.5), the player language is still being taken as Portuguese even after setting it to English.

**Comment by Lucasmg37** [comment]
@AayushGour
I added two new values in the player.

Now, you can use playbackRateOptions and playbackRateStart.

See more info at https://github.com/Lucasmg37/react-netflix-player#playbackrateoptions-

**Comment by AayushGour** [comment]
Thank you @Lucasmg37
