### ISSUE TITLE
ReferenceError react is not defined

### ISSUE THREAD

**Issue by ridhwaans** [Lucasmg37/react-netflix-player#41]
Hi @Lucasmg37 

I am trying out the new version but 

```
ReferenceError
react is not defined
eval
https://2v37wj.csb.app/node_modules/react-netflix-player/dist/ReactNetflixPlayer.js:1:348
$csb$eval
https://2v37wj.csb.app/node_modules/react-netflix-player/dist/ReactNetflixPlayer.js:1:14623
H
https://codesandbox.io/static/js/sandbox.d75da7eb7.js:1:100039
K.evaluate
https://codesandbox.io/static/js/sandbox.d75da7eb7.js:1:112791
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.d75da7eb7.js:1:123173
c
https://codesandbox.io/static/js/sandbox.d75da7eb7.js:1:112406
$csb$eval
/src/components/Player/index.js:3
> 3 | import ReactNetflixPlayer from "react-netflix-player";

ERROR in ./src/components/Player/index.js 8:0-54

Module not found: Error: Can't resolve 'react-netflix-player' in './src/components/Player'
```
Found this related thread
https://stackoverflow.com/questions/32070303/uncaught-referenceerror-react-is-not-defined

They are saying the solution is to either remove `externals: { 'react': 'React' }` in webpack.config, (so React will be bundled with your javascript) or load the React framework externally before this file is executed

Help me investigate?
reproducible sandbox -> https://codesandbox.io/s/debugging-2v37wj?file=/package.json

Thank you

**Comment by Lucasmg37** [comment]
Hey @ridhwaans 
Today I send a new version: 1.2.0

- I migrated the project to TS and add the types.
- I Removed webpack and configured Rollup in the project.

I tryed this with React 18 and works fine.
Just one point, at that new version, the import changed, now you can import the component like `import { ReactNetflixPlayer } from "react-netflix-player"`

Thanks for your feedback.
After test, please, say me if this resolved his problem.
