### ISSUE TITLE
Funciona na web?

### ISSUE THREAD

**Issue by bencok** [Lucasmg37/react-netflix-player#48]
Olá Lucas, beleza?
Mano, esse player é top das galaxias kkk, existe alguma forma de usar ele na web? seja usando php ou html+css+java+php

Abraços.

**Comment by Lucasmg37** [comment]
Opa @bencok 

De pendendendo da forma como você está trabalhando com php, seja possível, desde de que você trabalhe com  React na parte de renderização.

Mas será necessário arrumar um modo de que as partes se comuniquem.

**Comment by bencok** [comment]
meu site é full php, tu manja como eu faria para usar ele?

**Comment by Advansoftware** [comment]
- Criar uma aplicação React separada que use o react-netflix-player como um componente. 
 Você pode seguir as instruções do [repositório](https://github.com/Lucasmg37/react-netflix-player) do projeto para instalar e configurar o componente.
- Criar uma API REST em PHP que forneça os dados necessários para o player, como os links dos vídeos, os títulos, as legendas, etc. 
Você pode usar algum framework como o Laravel ou o Slim para facilitar esse processo.
- Usar o axios ou outro cliente HTTP no React para fazer as requisições na API e obter os dados para o player.
- Usar o react-router ou outro pacote para criar rotas no React que correspondam aos vídeos que você quer mostrar no player.
- Gerar um build da aplicação React usando o comando npm run build ou yarn build. Isso vai criar uma pasta chamada build com os arquivos estáticos do React.
- Copiar a pasta build para o seu servidor PHP e configurar o seu .htaccess ou outro arquivo de configuração para servir os arquivos estáticos do React e redirecionar as requisições para a API PHP.

Essa é uma forma simples de integrar o React com o PHP, mas existem outras formas mais avançadas, como usar o SSR (Server Side Rendering) ou o SSG (Static Site Generation) para melhorar o desempenho e a SEO da sua aplicação.

**Comment by bencok** [comment]
Entendi mas não sei como fazer isso porque é muito difícil pra mim que estou começando, então vou deixar isso de lado, mas obrigado pela atenção.
